### PR TITLE
Strip GPG signature information from date

### LINKED ISSUE #154: Commits signed with GPG lead to JSONDecodeError
I discovered this bug in [this commit](https://gitlab.com/carmenbianca/schaakmat/tree/7a99f12819e9b4734a8fa48e726cd501cc96f8e8) on my project.

To reproduce in any other project:

- `git commit --alow-empty --gpg-sign=$YOUR_KEYID -m "empty signed commit"`
- `python setup.py sdist`
- `cd dist`
- `pip install $YOUR_TAR_FILE`
- Then open Python and import your project, you will see:
  ```
  >>> import schaakmat
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/carmen/Projects/schaakmat/dist/schaakmat-0.1.0+206.g7a99f12/src/schaakmat/__init__.py", line 53, in <module>
      __version__ = get_versions()['version']
    File "/home/carmen/Projects/schaakmat/dist/schaakmat-0.1.0+206.g7a99f12/src/schaakmat/_version.py", line 21, in get_versions
      return json.loads(version_json)
    File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
      obj, end = self.scan_once(s, idx)
  json.decoder.JSONDecodeError: Invalid control character at: line 3 column 59 (char 61)
  ```

The output in the _version.py file:

    # This file was generated by 'versioneer.py' (0.18) from
    # revision-control system data, or from the parent directory name of an
    # unpacked source archive. Distribution tarballs contain a pre-generated copy
    # of this file.

    import json

    version_json = '''
    {
    "date": "gpg:TSignaturemade Sat 03 Jun 2017 12:11:07 CEST\ngpg:                using RSA key 68ECFDA761AB8763CB579CFA76EBA6F6B6EA2EC9\ngpg: Good signature from \"Carmen Bianca Bakker <carmen@carmenbianca.eu>\" [ultimate]\ngpg:                 aka \"Carmen Bianca Bakker <c.b.bakker@carmenbianca.eu>\" [ultimate]\ngpg:                 aka \"Carmen Bianca Bakker <bakk1302@student.nhl.nl>\" [ultimate]\nPrimary key fingerprint: 2A09 F627 39F6 DEC8 CFFC  A216 CD0A 90F1 C5CA 0C92\n     Subkey fingerprint: 68EC FDA7 61AB 8763 CB57  9CFA 76EB A6F6 B6EA 2EC9\n2017-06-03 12:09:47 +0200",
    "dirty": false,
    "error": null,
    "full-revisionid": "7a99f12819e9b4734a8fa48e726cd501cc96f8e8",
    "version": "0.1.0+206.g7a99f12"
    }
    '''  # END VERSION_JSON

    def get_versions():
        return json.loads(version_json)

The 'date' name has a broken value.

I'll tinker a little bit to see if I can fix this and submit a merge request. No promises, though.

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #154

I was only able to fix this in from_cvs.py so far. I don't really know how to fix this in the other sections, to be honest. It probably comes down to `date = date.strip("\n")[-1]` again, but I frankly don't know where.

### CODE REVIEW

**Comment by carmenbianca** [comment]
I think this is it :) I just don't know the codebase too well to know whether this covers all bases.

**Comment by carmenbianca** [comment]
Or maybe not :( I'm breaking Travis and I don't know why. I am thinking it doesn't like the use of `"\n"` in the file? I really don't know. Either way it's just the tests that break for me, not the program itself.

**Comment by carmenbianca** [comment]
Fixed :) Some of it, at least. There's still an error in the tests remaining, but when I run the tests locally on the master branch, the same tests fail. So I think this about does it?

**Comment by jayvdb** [comment]
The Travis errors are due to the new pydocstyle, and should be fixed with https://github.com/warner/python-versioneer/pull/157

**Comment by carmenbianca** [comment]
Thanks!  You are right.

**Comment by thurask** [comment]
Converting the date stamp from ISO 8601-like to actual ISO 8601 (i.e. the `replace` chain) happens before extracting the last line in `from_keywords.py` but after extracting the last line on `from_vcs.py`; I think it should be after to make sure nothing is mistakenly applied to the part that should be stripped out.

**Comment by carmenbianca** [comment]
@thurask Agreed.

**Comment by warner** [comment]
Hey, thanks, this looks good. Could you do two things?:

* rebase to current master (which should fix the travis problem), also squash down to one commit
* add a test?

I think the new tests should go into `test/git/test_git.py`. The `Keywords` class could be enhanced to add a `["date"]` key to the dict that it passes into `git_versions_from_keywords`, and the test should exercise all of (no date, single-line date, multi-line date).

The `from_vcs` side can be tested in `ParseGitDescribe.test_pieces` by changing the way `fake_run_command` works when it is run with `rev-parse`, and again we should exercise all the possible options.

thanks!

**Comment by carmenbianca** [comment]
Something like that.

I dislike rebasing and force-pushing, but there you go.

I haven't the faintest idea how to go about returning no date from `git-show`, so that test was not implemented.

**Comment by carmenbianca** [comment]
And of course some tests fail.  I had initially assumed that master was broken as it was last time, but apparently some of my changes (I assume in `Keywords.parse`) broke a couple of tests.  I do not know how to fix those tests, because not a single line of code I touched should affect the version output of `git_versions_from_keywords`.

**Comment by effigies** [comment]
We're working on reviving this project. Can you rebase/merge master to refresh the CI?

**Comment by pdecat** [comment]
I've rebased this branch and fixed unit tests in #222.

**Pull request closed without merging**
