### PR TITLE
Add branch as optional key to reported versions

### PR DESCRIPTION
**Pull request by foosel**
This should provide the branch a release was built from as
part of the reported version data, allowing to access it from
within the application embedding versioneer and at least
displaying it somewhere.

I've been using something like that for over a year now with
OctoPrint, just thought it might be time to try to port it
to the current versioneer version and share it while in the
process ;)

Note: I did adjust (and run) the test suite. I had two errors
with `test_invocations.py`, however I had the very same 
two errors on the `master` branch without my changes as 
well so I don't think I caused them:

```
======================================================================
ERROR: test_build (__main__.DistutilsRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/git/test_invocations.py", line 273, in test_build
    data = versions_from_file(fn)
  File "src/from_file.py", line 30, in versions_from_file
    raise NotThisMethod("unable to read _version.py")
NotThisMethod: unable to read _version.py

======================================================================
ERROR: test_build (__main__.DistutilsUnpacked)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/git/test_invocations.py", line 475, in test_build
    data = versions_from_file(fn)
  File "src/from_file.py", line 30, in versions_from_file
    raise NotThisMethod("unable to read _version.py")
NotThisMethod: unable to read _version.py

----------------------------------------------------------------------
Ran 34 tests in 56.129s
```

### CODE REVIEW

**Comment by foosel** [comment]
Also see #49 (which I wasn't aware of before preparing this)

**Comment by foosel** [comment]
Ran the tests... but forgot the linter... sorry for that, fixing...

**Comment by foosel** [comment]
Is there an interest in this? If not just tell me, no harm done, but it would safe me some trouble/allow me to just maintain my own fork with the stuff I need without having to polish it for general consumption :)

**Comment by pelson** [comment]
@foosel - I did something similar in #90. I'm ok with either approach, but believe that the branch is paramount to determining an appropriate version.

**Comment by foosel** [comment]
@pelson I agree. Funny enough I've been doing something similar to your #90 also, see [here](https://github.com/foosel/python-versioneer/commit/2a1f4e37f1b4120a08f69e978a537307c4dd7ae2). Based on a lookup file with which I can define "virtual" tags per branch regex and also override the version renderer. Didn't want to submit it though before the branch stuff was clarified, since without that it doesn't make sense since - as you say - the branch is paramount.

**Pull request closed without merging**
