### PR TITLE
Further fix tests by using setuptools copy of 'bdist_wheel' functions, if available

### PR DESCRIPTION
**Pull request by Callek**

### CODE REVIEW

**Comment by Callek** [comment]
Noticed this when reviewing #394

**Comment by Callek** [comment]
While I can merge this without review - I'm a big fan of reviews on code changes, even my own.

@mwtoews (you emoji reacted here) and @sudhackar (most recent person to submit a PR) -  Do either of you want to review this in @effigies 's current absense?

**Review by mwtoews — APPROVED** [review]
Using a recent version of `wheel`, the original import raises an exception:
```pycon
>>> import wheel
>>> wheel.__version__
'0.44.0'
>>> from wheel.bdist_wheel import get_abi_tag, get_platform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'get_abi_tag' from 'wheel.bdist_wheel' (/path/to/wheel/bdist_wheel.py)
```
This PR resolves this ImportError in a forward-compatible way.

---

My only nit is that the comment has mixed single `` ` ``  and double ` `` ` backticks. Maybe just use unquoted setuptools and wheel in the comments instead.

**Review by effigies — APPROVED** [review]
Looks reasonable, thanks for your patience.

**Comment by sudhackar** [comment]
LGTM too!

**Pull request merged**
