### PR TITLE
Fix tests and deprecation warnings

### PR DESCRIPTION
**Pull request by moggers87**
Tests are currently broken in master, this PR fixes that.

Most of the work was making sure that installed packages used for testing were old enough to work with EOL'd versions of Python.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Would be a good thing to merge this one as it will resolve `DeprecationWarning: invalid escape sequence` in the generated `versioneer.py`.

**Comment by alimcmaster1** [comment]
@warner is it possible to take a look at this?

**Comment by effigies** [comment]
Closed and reopened to check whether this still fixes Travis...

**Comment by effigies** [comment]
Alas, things are failing. If you care to have another go at this, please do. Otherwise I'll have a look this next week.

**Pull request closed without merging**
