### PR TITLE
hide console window if pythonw.exe is used

### PR DESCRIPTION
**Pull request by CSchulzeTLK**
This should solve the isse #284

### CODE REVIEW

**Comment by effigies** [comment]
Should be able to fix the tests by merging/rebasing master. Though might be worth waiting on #283 (or rebasing on that) to get Windows tests too.

**Comment by CSchulzeTLK** [comment]
Yes, I'm still using 0.20 due to 283, and couldn't benefit from the changes of this pull request.

**Comment by effigies** [comment]
#283 is merged. Could you merge/rebase `master`? I think your test failures are related to some things we fixed over there.

**Comment by effigies** [comment]
Tests passing. Looks great. Thanks for the PR!

**Pull request merged**
