### PR TITLE
Added new styles to mark branches as pre releases

### PR DESCRIPTION
**Pull request by tlusk**
This adds two new styles `pep440-branch` and `pep440-post-branch` which
mark all versions generated from non master branches with a version
compatible with `pip --pre`.

These formats are useful if you want to publish all CI builds to a pypi
repository but don't want feature branch builds to be pulled
automatically ahead of the master branch with `pip install`.

### CODE REVIEW

**Comment by jcfr** [comment]
@warner  Do you think this could be merged ? Tests are passing and feature is documented.

**Comment by effigies** [comment]
We're working on reviving this project. Can you rebase/merge master to resolve conflicts and refresh the CI?

**Comment by tlusk** [comment]
@effigies all set

**Review by effigies — APPROVED** [review]
This looks well written and tested to me...

**Comment by effigies** [comment]
Sorry, this is conflicting with another recent merge. Could you try another rebase?

**Comment by tlusk** [comment]
@effigies all set

**Comment by effigies** [comment]
Thanks!

**Pull request merged**
