### PR TITLE
FIX: Construct binary wheel filenames consistently for Python and Pypy

### PR DESCRIPTION
**Pull request by pkittenis**
Continued from #223

Fix PyPy binary wheel names and tests.

### CODE REVIEW

**Comment by pkittenis** [comment]
All setuptools, pip and packaging needed updating in tox.

**Comment by effigies** [comment]
Looks like it's [still failing](https://travis-ci.com/github/python-versioneer/python-versioneer/jobs/403395654)?

**Comment by pkittenis** [comment]
`test_extension_wheel_setuptools (__main__.SetuptoolsUnpacked) ... FAIL` :disappointed: 

Will take another look tomorrow - cannot reproduce failure locally.

**Comment by effigies** [comment]
Cool. If I find some time, I'll see if I can get a reliable conda-based reproduction. Thanks for working through this, btw.

**Comment by pkittenis** [comment]
Looks [ok now](https://travis-ci.com/github/python-versioneer/python-versioneer/jobs/403440947), needed wheel as well in tox.

By locally I meant outside tox - tox is too slow to run locally for me.
Prefer to have the CI run different interpreters, faster, less configuration and allows for tests to be run locally.

**Comment by effigies** [comment]
Ah, excellent. Thanks so much for tracking this down. I'm glad it turned out to be just a matter of dependency versions.

I agree, I'm finding tox a bit painful to use (I've just been `source .tox/pypy3/bin/activate`ing to do my one-off tests), but I don't want to try to shift away before getting a release out.

Thanks again for this.

**Pull request merged**
